---
# FIXME: Uncomment after done testing
# - name: System Upgrade
#   become: true
#   ansible.builtin.dnf:
#     name: "*"
#     state: latest # noqa package-latest
- name: "Install System Tools"
  become: true
  ansible.builtin.dnf:
    name:
      - "neovim"
      - "NetworkManager-tui"
      - "glances"
      - "zsh"
    state: present
- name: Install Oh-My-Zsh
  ansible.builtin.import_role:
    name: gantsign.oh-my-zsh
  vars:
    oh_my_zsh_theme: amuse
    oh_my_zsh_plugins:
      - git
      - zsh-syntax-highlighting
    oh_my_zsh_update_mode: auto
    oh_my_zsh_frequency: 10
    users:
      - username: "{{ ansible_env.USER }}"
        theme: amuse
        plugins:
          - git
          - zsh-syntax-highlighting
        update_mode: auto
        update_frequency: 10
- name: "Install Oh-My-Zsh custom scripts"
  ansible.builtin.copy:
    src: files/zsh-custom/
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: preserve
- name: "Install zsh-syntax-highlighting"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    update: true
    accept_newhostkey: true
    single_branch: true
- name: "Symlink vim to nvim"
  become: true
  ansible.builtin.file:
    src: /usr/bin/nvim
    dest: /usr/bin/vim
    state: link
