---
- name: Enable SwayNotificationCenter COPR Repository
  become: true
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: erikreider/SwayNotificationCenter
- name: Install Desktop Packages
  become: true
  ansible.builtin.dnf:
    name:
      - sway
      - swaylock
      - wofi
      - waybar
      - swayidle
      - grimshot
      - SwayNotificationCenter
      - NetworkManager-tui
      - alacritty
      - gammastep
      - brightnessctl
      - linux-libertine-fonts
      - google-noto-emoji-color-fonts
      - fontawesome-fonts
      - fontawesome-fonts-web
      - fontawesome5-fonts
      - fontawesome5-free-fonts
    state: present
- name: Install Desktop Flatpaks
  community.general.flatpak:
    name:
      - org.signal.Signal
    method: user
    state: present
- name: Install Desktop Configurations
  ansible.builtin.copy:
    src: files/config/
    dest: "{{ ansible_env.HOME }}/.config/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: preserve
- name: Install Custom Desktop Entries
  ansible.builtin.copy:
    src: files/applications/
    dest: "{{ ansible_env.HOME }}/.local/share/applications/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: preserve
- name: Enable Gammastep Service
  ansible.builtin.systemd:
    name: "gammastep.service"
    scope: "user"
    enabled: true
    daemon_reload: true
- name: Enable Notification Center Service
  ansible.builtin.systemd:
    name: "swaync.service"
    scope: "user"
    enabled: true
    daemon_reload: true
- name: Download Desktop Wallpaper
  ansible.builtin.get_url:
    url: https://wallpaperaccess.com/download/orange-polygon-692137
    dest: "{{ ansible_env.HOME }}/Pictures/orange-polygon-material-wallpaper.png"
    mode: "0644"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
- name: Link Current Wallpaper
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/Pictures/orange-polygon-material-wallpaper.png"
    dest: "{{ ansible_env.HOME }}/Pictures/desktop-background"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0600"
    state: link
- name: Updating fontconfig cache
  ansible.builtin.command: fc-cache -f
  changed_when: true
- name: Install Brave Web Apps
  include_role:
    name: "install_pwa"
  vars:
    app: "{{ item }}"
  loop:
    - name: "messages.google.com"
      manifest_url: "https://messages.google.com/web/manifest.json"
      profile: "Personal"
    - name: "spotify.com"
      manifest_url: "https://open.spotifycdn.com/cdn/generated/manifest-web-player.3a6f5207.json"
      profile: "Personal"
