---
- name: Enable SwayNotificationCenter COPR Repository
  become: true
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: erikreider/SwayNotificationCenter
- name: Install Desktop Packages
  become: true
  ansible.builtin.dnf:
    name:
      - sway
      - swaylock
      - wofi
      - waybar
      - swayidle
      - grimshot
      - SwayNotificationCenter
      - NetworkManager-tui
      - alacritty
      - gammastep
      - brightnessctl
    state: present
- name: Install Desktop Configurations
  ansible.builtin.copy:
    src: files/
    dest: "{{ ansible_env.HOME }}/.config/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: preserve
- name: Enable Gammastep Service
  ansible.builtin.systemd:
    name: "gammastep.service"
    scope: "user"
    enabled: true
    daemon_reload: true
- name: Enable Notification Center Service
  ansible.builtin.systemd:
    name: "swaync.service"
    scope: "user"
    enabled: true
    daemon_reload: true
- name: Download Desktop Wallpaper
  ansible.builtin.get_url:
    url: https://wallpaperaccess.com/download/orange-polygon-692137
    dest: "{{ ansible_env.HOME }}/Pictures/orange-polygon-material-wallpaper.png"
- name: Link Current Wallpaper
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/Pictures/orange-polygon-material-wallpaper.png"
    dest: "{{ ansible_env.HOME }}/Pictures/desktop-background"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.GROUP }}"
    mode: "0600"
    state: link
